In [2]:
import tensorflow as tf


In [15]:
# constant tensor
c1 = tf.constant(10)
c1

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [17]:
c2 = tf.constant(10,tf.int16)
c2

<tf.Tensor: shape=(), dtype=int16, numpy=10>

In [21]:
c3 = tf.constant(10,tf.int16,name='Suresh')
c3

<tf.Tensor: shape=(), dtype=int16, numpy=10>

In [26]:
# constant tensor with float dtype
c4 = tf.constant(10.2, dtype=float)
c4

<tf.Tensor: shape=(), dtype=float32, numpy=10.2>

### Variable tensor

In [3]:
v1 = tf.Variable(25)
v1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25>

### change the value of tensor usign assign()



In [4]:
v1.assign(45)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=45>

In [28]:
# string constant tensor
c5 = tf.constant("hello world")
c5

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>