In [1]:
import tensorflow as tf

### creating tensor with arrays

#### 1d array

In [9]:
arr1 = tf.constant([1,2,3,4])
arr1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

#### 2d array

In [10]:
arr2 = tf.constant([[1,2,3,4],[6,7,8,9]])
arr2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [6, 7, 8, 9]])>

In [22]:
arr2 = tf.Variable([[1,2,3,4,5],[5,6,7,8,4]])
arr2

<tf.Variable 'Variable:0' shape=(2, 5) dtype=int32, numpy=
array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 4]])>

In [23]:
arr2.name

'Variable:0'

In [24]:
arr2.shape

TensorShape([2, 5])

In [25]:
arr2.dtype

tf.int32

#### 3d array


In [27]:
arr3 = tf.Variable([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[0,1,2]]
])
arr3

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])>

In [28]:
arr3.shape

TensorShape([2, 2, 3])